language: node_js
sudo: required
services:
- docker
matrix:
  include:
    - node_js: '6'
      env: NODE_VERSION=6
    - node_js: '8'
      env: NODE_VERSION=8
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  on:
    tags: true
    repo: xogroup/bunnybus
  api_key:
    secure: e5f704c5tL5na67NsVXWQ4j3fWJIrclgh23MSIDejAB2D25bT6Sj0aSLGyptAk9AQvvOTjw7OoP/+R+oPMPVGZzRXhAb7+jsf3ElC2KcLLJNjx2VA84jmnh4RA+BJd+Vxb1BCtAMNd+81LjbJD7xo3mj91r+bFj0Vi9ZQSLTXpF2KfaJezyZ1L2TJ2HmqwrDOHKV8G02xJcuHxcym2ibuXdYe+ehhO3xFPQy9w1grEduliSQPtoRUkCMN/OwKl+d43J9fJaLfaMMpfVo5osO6vOBV+yuHz3bacp67mspDe7AdERq2Vn3ixlGxd//t0tZU8F30gFW9Z05/PssfKhZ4+e2sZfPRLFLnWV55ab8gfle4Q9dAYS+2vnSpLHdVBrKC2Yry9xCU9a3s08PNnFDQSr9e9WJXbw2hyIagTdBVmdihKNAhTCLJKxewatf7RaLhLSfIu5RDi6oxixVyUl7kl96JnCQjliIX7xBDBtSLCYrmcreSJSwSQxYUe0haTX9GmvWDJXjKc/ivd9TKqPFqtUNSH1LAckor6vg5QKUbbAazUyhEKI8L9Yl69PI0AjL2ntzPlOU3pZ2dipxQ8/gjlE+aZMMW3qUpMp4S+HQZnSvsOfpIywwlvvob1McbYCSvSXGciGfUdMzVeDVql2qNq14/o4IIMvY8VY9rVjuqP4=
before_install:
- npm install -g npm@'>=2.13.5'
- docker pull rabbitmq:3-management
- docker run -d -p 5671:5671 -p 15672:15672 -p 5672:5672 rabbitmq:3-management
script: npm run build-test
notifications:
  slack:
    secure: dN/RtoOlePaaMHWEzcmdBslIvIig9/b8YE7Ej++XTvsgzL5EGHyrhk2u6BEkAX1bVprPBAhNCJaTTvJ6DNdibbTHv3sy+q51wg+tpWIDMuDCjLyZhGbvR+yKEblnM41a0AzEXP0tt9ijv4yoxc4LAsSkFOk1PNFr68yiEdM+see5B2AbixM4BDqZiYxfVv/uEq1nEfrRbSB9Q+UOO4i+eQyYroLEAtTM1t8qS7kBk+QkMLSCkH4O/gvu6Yhb0esPfqm0ju90/FdtZCRsy9+FV7JUjTI8qfd9VqgIkRrFKpjwTnPwu+FJduXmz9jnfdXVKIhkZicKnd/A0Ncsq2lUZeGlrWtCKBY54lLZ9yI3UG9y0v+xjUnBcLLC5Fmr58BSgQrMEoqdCqDoPJtvWVsKjO6hshHc37Y6mqVIUfjGwsDjq8fR77Rk8ZCxb7Eb8pDwBRt/21cjsdgZ9k3tUn5nog3yl5iVKgBTBQOkxo9TKmjCs+j6tN74xNRs/TiK22fnnNhlxrobwK/Kdg9hOcwTLIjnTMGvuuGnQpjM2GNeTPxt55hvx6gv+KQL3azERZzYAY+7K0X+jubrnUTmSEsOjkDfZL3/mL3yHx3wCYmIynpsTo9il7rojQVEQ+NhBsapRNjhZkjo/dXW8l9fEdkiX/BM1pFE28c56B6LdMZckUs=
